/**
 * HoneyBadger-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HoneyBadgerApi) {
      root.HoneyBadgerApi = {};
    }
    root.HoneyBadgerApi.Booking = factory(root.HoneyBadgerApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Booking model module.
   * @module model/Booking
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Booking</code>.
   * @alias module:model/Booking
   * @class
   * @param userId {String} 
   */
  var exports = function(userId) {
    var _this = this;



    _this['userId'] = userId;


  };

  /**
   * Constructs a <code>Booking</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Booking} obj Optional instance to populate.
   * @return {module:model/Booking} The populated <code>Booking</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('serviceId')) {
        obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'String');
      }
      if (data.hasOwnProperty('serviceName')) {
        obj['serviceName'] = ApiClient.convertToType(data['serviceName'], 'String');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
      if (data.hasOwnProperty('userFirstName')) {
        obj['userFirstName'] = ApiClient.convertToType(data['userFirstName'], 'String');
      }
      if (data.hasOwnProperty('userLastName')) {
        obj['userLastName'] = ApiClient.convertToType(data['userLastName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} serviceId
   */
  exports.prototype['serviceId'] = undefined;
  /**
   * @member {String} serviceName
   */
  exports.prototype['serviceName'] = undefined;
  /**
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * @member {String} userFirstName
   */
  exports.prototype['userFirstName'] = undefined;
  /**
   * @member {String} userLastName
   */
  exports.prototype['userLastName'] = undefined;



  return exports;
}));


